// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.2
// client: pb/kakaku.proto

package kakaku

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AssetPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base  string `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote string `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *AssetPriceRequest) Reset() {
	*x = AssetPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_kakaku_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPriceRequest) ProtoMessage() {}

func (x *AssetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kakaku_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPriceRequest.ProtoReflect.Descriptor instead.
func (*AssetPriceRequest) Descriptor() ([]byte, []int) {
	return file_pb_kakaku_proto_rawDescGZIP(), []int{0}
}

func (x *AssetPriceRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *AssetPriceRequest) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

type AssetPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base      string               `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Quote     string               `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Price     string               `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AssetPriceResponse) Reset() {
	*x = AssetPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_kakaku_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPriceResponse) ProtoMessage() {}

func (x *AssetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kakaku_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPriceResponse.ProtoReflect.Descriptor instead.
func (*AssetPriceResponse) Descriptor() ([]byte, []int) {
	return file_pb_kakaku_proto_rawDescGZIP(), []int{1}
}

func (x *AssetPriceResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *AssetPriceResponse) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *AssetPriceResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *AssetPriceResponse) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_pb_kakaku_proto protoreflect.FileDescriptor

var file_pb_kakaku_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x6b, 0x61, 0x6b, 0x61, 0x6b, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6b, 0x61, 0x6b, 0x61, 0x6b, 0x75, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x11, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0x55, 0x0a, 0x0e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0a,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x6b, 0x61, 0x6b,
	0x61, 0x6b, 0x75, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6b, 0x61, 0x6b, 0x61, 0x6b, 0x75, 0x2e, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x2d, 0x6a, 0x61, 0x70, 0x61, 0x6e, 0x2f, 0x6b, 0x61, 0x6b, 0x61,
	0x6b, 0x75, 0x2f, 0x70, 0x62, 0x2f, 0x6b, 0x61, 0x6b, 0x61, 0x6b, 0x75, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_kakaku_proto_rawDescOnce sync.Once
	file_pb_kakaku_proto_rawDescData = file_pb_kakaku_proto_rawDesc
)

func file_pb_kakaku_proto_rawDescGZIP() []byte {
	file_pb_kakaku_proto_rawDescOnce.Do(func() {
		file_pb_kakaku_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_kakaku_proto_rawDescData)
	})
	return file_pb_kakaku_proto_rawDescData
}

var file_pb_kakaku_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_kakaku_proto_goTypes = []interface{}{
	(*AssetPriceRequest)(nil),   // 0: kakaku.AssetPriceRequest
	(*AssetPriceResponse)(nil),  // 1: kakaku.AssetPriceResponse
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pb_kakaku_proto_depIdxs = []int32{
	2, // 0: kakaku.AssetPriceResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: kakaku.CheckinService.AssetPrice:input_type -> kakaku.AssetPriceRequest
	1, // 2: kakaku.CheckinService.AssetPrice:output_type -> kakaku.AssetPriceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_kakaku_proto_init() }
func file_pb_kakaku_proto_init() {
	if File_pb_kakaku_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_kakaku_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_kakaku_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_kakaku_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_kakaku_proto_goTypes,
		DependencyIndexes: file_pb_kakaku_proto_depIdxs,
		MessageInfos:      file_pb_kakaku_proto_msgTypes,
	}.Build()
	File_pb_kakaku_proto = out.File
	file_pb_kakaku_proto_rawDesc = nil
	file_pb_kakaku_proto_goTypes = nil
	file_pb_kakaku_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CheckinServiceClient is the client API for CheckinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckinServiceClient interface {
	AssetPrice(ctx context.Context, in *AssetPriceRequest, opts ...grpc.CallOption) (*AssetPriceResponse, error)
}

type checkinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckinServiceClient(cc grpc.ClientConnInterface) CheckinServiceClient {
	return &checkinServiceClient{cc}
}

func (c *checkinServiceClient) AssetPrice(ctx context.Context, in *AssetPriceRequest, opts ...grpc.CallOption) (*AssetPriceResponse, error) {
	out := new(AssetPriceResponse)
	err := c.cc.Invoke(ctx, "/kakaku.CheckinService/AssetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckinServiceServer is the server API for CheckinService service.
type CheckinServiceServer interface {
	AssetPrice(context.Context, *AssetPriceRequest) (*AssetPriceResponse, error)
}

// UnimplementedCheckinServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCheckinServiceServer struct {
}

func (*UnimplementedCheckinServiceServer) AssetPrice(context.Context, *AssetPriceRequest) (*AssetPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssetPrice not implemented")
}

func RegisterCheckinServiceServer(s *grpc.Server, srv CheckinServiceServer) {
	s.RegisterService(&_CheckinService_serviceDesc, srv)
}

func _CheckinService_AssetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckinServiceServer).AssetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kakaku.CheckinService/AssetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckinServiceServer).AssetPrice(ctx, req.(*AssetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckinService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kakaku.CheckinService",
	HandlerType: (*CheckinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssetPrice",
			Handler:    _CheckinService_AssetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/kakaku.proto",
}
